name: practical4
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+5

environment:
  sdk: '>=2.19.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/image/

  fonts:
    - family: Noto
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf

    - family: orbit
      fonts:
        - asset: assets/fonts/Orbitron-Regular.ttf
  
  
  
  
  
